export const ADD_BUNS = "DRAG_BUNS";
export const ADD_OTHER_INGREDIENTS = "DRAG_OTHER_INGREDIENT";
export const DELETE_CONSTRUCTOR_INGREDIENT = "DELETE_CONSTRUCTOR_INGREDIENT";
export const SORT_INGREDIENTS = "SORT_INGREDIENTS";
export const RESET_CONSTRUCTOR = 'RESET_CONSTRUCTOR';